services:
  - type: web
    name: event-trek
    env: static
    buildCommand: cd frontend && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
